# Generated by Django 6.1 on 2026-09-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='estimated_price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
