# Generated by Django 6.1 on 2026-09-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='message',
            new_name='counter_message',
        ),
        migrations.AddField(
            model_name='quotation',
            name='counter_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
