# Generated by Django 6.1 on 2026-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_message_quotation_counter_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='final_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
