# Generated by Django 6.1 on 2026-09-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_savedprovider'),
        ('services', '0006_quotation_final_message_quotation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='services.service')),
            ],
            options={
                'ordering': ['service__name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'service'), name='unique_provider_service')],
            },
        ),
    ]
