# Generated by Django 6.1 on 2026-09-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
