# Generated by Django 6.1 on 2026-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
